name: Add Label to Issue

on:
    issues:
        types: [opened]
jobs:
    add-label-to-issue:
        name: Add label to this issue
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v8
              with:
                script: |
                  github.rest.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Bug']
                  })
    add-assignee-to-issue:
        name: Add assignee to this issue
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v8
              with:
                script: |
                  github.rest.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    assignees: [context.actor]
                  })
